updated PyTorch container

diff --git a/Dockerfile.pytorch b/Dockerfile.pytorch
--- a/Dockerfile.pytorch
+++ b/Dockerfile.pytorch
@@ -32,7 +32,7 @@ RUN apt-get update && \
             python3-pip \
 		  python3-dev \
 		  libopenblas-dev \
-		  libopenmpi3 \
+		  libopenmpi-dev \
             openmpi-bin \
             openmpi-common \
 		  gfortran \
@@ -63,10 +63,9 @@ RUN wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certif
 # torchvision 0.4
 #
 ARG TORCHVISION_VERSION=v0.4.0
-ARG PILLOW_VERSION=pillow<7
-ARG TORCH_CUDA_ARCH_LIST="7.2;8.7"
+ARG TORCH_CUDA_ARCH_LIST="5.3;6.2;7.2;8.7"
 
-RUN printenv && echo "torchvision version = $TORCHVISION_VERSION" && echo "pillow version = $PILLOW_VERSION" && echo "TORCH_CUDA_ARCH_LIST = $TORCH_CUDA_ARCH_LIST"
+RUN printenv && echo "torchvision version = $TORCHVISION_VERSION" && echo "TORCH_CUDA_ARCH_LIST = $TORCH_CUDA_ARCH_LIST"
 
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
@@ -84,7 +83,8 @@ RUN git clone -b ${TORCHVISION_VERSION} https://github.com/pytorch/vision torchv
     rm -rf torchvision
 
 # note:  this was used on older torchvision versions (~0.4) to workaround a bug,
-#        but has since started causing another bug as of torchvision 0.11.1    
+#        but has since started causing another bug as of torchvision 0.11.1
+# ARG PILLOW_VERSION=pillow<7    
 # pip3 install --no-cache-dir "${PILLOW_VERSION}"
 
 
@@ -141,9 +141,12 @@ RUN apt-get update && \
 RUN pip3 install --no-cache-dir scikit-build && \
     pip3 install --no-cache-dir ninja && \
     pip3 install --no-cache-dir --verbose pysoundfile
-    
+
+# note:  see https://github.com/pytorch/audio/issues/2295 for the reason for the sed commands
 RUN git clone --recursive -b ${TORCHAUDIO_VERSION} https://github.com/pytorch/audio torchaudio && \
     cd torchaudio && \
+    sed -i 's#  URL https://zlib.net/zlib-1.2.11.tar.gz#  URL https://zlib.net/zlib-1.2.12.tar.gz#g' third_party/zlib/CMakeLists.txt || echo "failed to patch torchaudio/third_party/zlib/CMakeLists.txt" && \
+    sed -i 's#  URL_HASH SHA256=c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1#  URL_HASH SHA256=91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9#g' third_party/zlib/CMakeLists.txt || echo "failed to patch torchaudio/third_party/zlib/CMakeLists.txt" && \
     BUILD_SOX=1 python3 setup.py install && \
     cd ../ && \
     rm -rf torchaudio
