added VPI and OpenCV to JetPack container

diff --git a/Dockerfile.jetpack b/Dockerfile.jetpack
--- a/Dockerfile.jetpack
+++ b/Dockerfile.jetpack
@@ -80,7 +80,48 @@ RUN apt-get update && \
     && rm -rf /var/lib/apt/lists/* \
     && apt-get clean
     
+
+#
+# install VPI
+#    
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+		  vpi2-dev \
+		  vpi2-demos \
+		  vpi2-samples \
+		  python3-vpi2 \
+		  python3-pip \
+		  python3-pil \
+    && rm -rf /var/lib/apt/lists/* \
+    && apt-get clean
     
+RUN pip3 install --no-cache-dir --verbose numpy
+    
+
+#
+# install OpenCV (with CUDA)
+#
+ARG OPENCV_URL=https://nvidia.box.com/shared/static/2hssa5g3v28ozvo3tc3qwxmn78yerca9.gz
+ARG OPENCV_DEB=OpenCV-4.5.0-aarch64.tar.gz
+
+RUN apt-get purge -y '*opencv*' || echo "previous OpenCV installation not found" && \
+    mkdir opencv && \
+    cd opencv && \
+    wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate ${OPENCV_URL} -O ${OPENCV_DEB} && \
+    tar -xzvf ${OPENCV_DEB} && \
+    dpkg -i --force-depends *.deb && \
+    apt-get update && \
+    apt-get install -y -f --no-install-recommends && \
+    dpkg -i *.deb && \
+    rm -rf /var/lib/apt/lists/* && \
+    apt-get clean && \
+    cd ../ && \
+    rm -rf opencv && \
+    PYTHON3_VERSION=`python3 -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}".format(*version))'` && \
+    cp -r /usr/include/opencv4 /usr/local/include/opencv4 && \
+    cp -r /usr/lib/python${PYTHON3_VERSION}/dist-packages/cv2 /usr/local/lib/python${PYTHON3_VERSION}/dist-packages/cv2
+
+ 
 #
 # clean-up apt repos
 #
