updated ROS containers

diff --git a/Dockerfile.ros.foxy b/Dockerfile.ros.foxy
--- a/Dockerfile.ros.foxy
+++ b/Dockerfile.ros.foxy
@@ -88,7 +88,7 @@ RUN python3 -m pip install -U \
 ARG OPENCV_URL=https://nvidia.box.com/shared/static/5v89u6g5rb62fpz4lh0rz531ajo2t5ef.gz
 ARG OPENCV_DEB=OpenCV-4.5.0-aarch64.tar.gz
 
-RUN apt-get purge -y '*opencv*' && \
+RUN apt-get purge -y '*opencv*' || echo "previous OpenCV installation not found" && \
     mkdir opencv && \
     cd opencv && \
     wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate ${OPENCV_URL} -O ${OPENCV_DEB} && \
@@ -100,7 +100,9 @@ RUN apt-get purge -y '*opencv*' && \
     rm -rf /var/lib/apt/lists/* && \
     apt-get clean && \
     cd ../ && \
-    rm -rf opencv
+    rm -rf opencv && \
+    cp -r /usr/include/opencv4 /usr/local/include/opencv4 && \
+    cp -r /usr/lib/python3.6/dist-packages/cv2 /usr/local/lib/python3.6/dist-packages/cv2
 	
 # 
 # compile yaml-cpp-0.6, which some ROS packages may use (but is not in the 18.04 apt repo)
