fix: text-generation-webui improvements

diff --git a/packages/llm/text-generation-webui/Dockerfile b/packages/llm/text-generation-webui/Dockerfile
--- a/packages/llm/text-generation-webui/Dockerfile
+++ b/packages/llm/text-generation-webui/Dockerfile
@@ -2,87 +2,81 @@
 # name: text-generation-webui
 # group: llm
 # config: config.py
-# depends: [transformers, auto_gptq, gptq-for-llama, exllama:v1, exllama:v2, llama_cpp:gguf]
+# depends: [transformers, bitsandbytes, auto_gptq, gptq-for-llama, exllama:v1, exllama:v2, llama_cpp:gguf]
 # requires: '>=34.1.0'
 # docs: docs.md
 #---
 ARG BASE_IMAGE
+
 FROM ${BASE_IMAGE}
 
-WORKDIR /opt
-
+# Define build arguments
 ARG OOBABOOGA_REF
 ARG OOBABOOGA_SHA
+ARG OOBABOOGA_ROOT_DIR="/opt/text-generation-webui"
+ARG OOBABOOGA_MODEL_DIR="/data/models/text-generation-webui"
+ARG FLASH_ATTENTION_BRANCH="v2.5.4"
+ARG LD_PRELOAD_LIBS=""
 
+# Check GitHub API for version information
 ADD https://api.github.com/repos/oobabooga/text-generation-webui/git/${OOBABOOGA_REF} /tmp/oobabooga_version.json
 
-RUN git clone https://github.com/oobabooga/text-generation-webui && \
-    cd text-generation-webui && \
-    git checkout ${OOBABOOGA_SHA}
+# Copy patch files
+COPY *.diff /tmp/
 
-RUN cd text-generation-webui && \
-    #sed 's|^numpy.*|numpy|g' -i requirements.txt && \
-    #sed 's|^accelerate.*|accelerate|g' -i requirements.txt && \
-    sed 's|^bitsandbytes.*|#bitsandbytes|g' -i requirements.txt && \
-    #sed 's|^fastapi.*|fastapi|g' -i requirements.txt && \
-    #sed 's|^safetensors.*|safetensors|g' -i requirements.txt && \
-    sed 's|^llama-cpp-python.*|llama-cpp-python|g' -i requirements.txt && \
-    sed 's|^exllamav2.*|exllamav2|g' -i requirements.txt && \
-    sed 's|^autoawq.*||g' -i requirements.txt && \
-    #sed 's|^transformers.*|transformers|g' -i requirements.txt && \
-    #sed 's|^optimum.*|optimum|g' -i requirements.txt && \
-    #sed 's|^pydantic.*|pydantic|g' -i requirements.txt && \
-    #sed 's|^aiofiles.*|aiofiles|g' -i requirements.txt && \
-    #sed 's|^gradio.*|gradio|g' -i requirements.txt && \
-    #sed 's|^gradio_client.*|gradio_client|g' -i requirements.txt && \
-    #sed 's|^peft.*|peft|g' -i requirements.txt && \
-    sed 's|^git+https://github.com/oobabooga/torch-grammar.git||g' -i requirements.txt && \
-    sed 's|^git+https://github.com/huggingface/transformers.*|transformers|g' -i requirements.txt && \
-    sed 's|^git+https://github.com/huggingface/peft|#git+https://github.com/huggingface/peft|g' -i requirements.txt && \
-    sed 's|^https://github.com/PanQiWei/AutoGPTQ|#https://github.com/PanQiWei/AutoGPTQ|g' -i requirements.txt && \
-    sed 's|^https://github.com/jllllll/ctransformers-cuBLAS-wheels.*|#https://github.com/jllllll/ctransformers-cuBLAS-wheels|g' -i requirements.txt && \
-    cat requirements.txt
-    
-RUN pip3 install --no-cache-dir --verbose -r text-generation-webui/requirements.txt
+# Install text-generation-webui
+RUN set -ex \
+    && git clone https://github.com/oobabooga/text-generation-webui "$OOBABOOGA_ROOT_DIR" \
+    && git -C "$OOBABOOGA_ROOT_DIR" checkout "$OOBABOOGA_SHA" \
+    # Fix requirements
+    && sed -i \
+        -e 's|^bitsandbytes.*|#bitsandbytes|g' \
+        -e 's|^llama-cpp-python.*|llama-cpp-python|g' \
+        -e 's|^exllamav2.*|exllamav2|g' \
+        -e 's|^autoawq.*||g' \
+        -e 's|^transformers.*|transformers|g' \
+        -e 's|^https://github.com/jllllll/ctransformers-cuBLAS-wheels.*|#https://github.com/jllllll/ctransformers-cuBLAS-wheels|g' \
+        "$OOBABOOGA_ROOT_DIR/requirements.txt" \
+    # Fix https://github.com/oobabooga/text-generation-webui/issues/4644
+    && sed 's|to(self\.projector_device)|to(self\.projector_device,dtype=self\.projector_dtype)|' -i "$OOBABOOGA_ROOT_DIR/extensions/multimodal/pipelines/llava/llava.py" \
+    # Add required dependencies
+    && echo "git+https://github.com/oobabooga/torch-grammar.git@main" >> "$OOBABOOGA_ROOT_DIR/requirements.txt" \
+    && echo "git+https://github.com/UKPLab/sentence-transformers.git@master" >> "$OOBABOOGA_ROOT_DIR/requirements.txt" \
+    # Create a symbolic link from /opt/GPTQ-for-LLaMa/*.py to oobabooga root dir
+    && ln -s /opt/GPTQ-for-LLaMa/*.py "$OOBABOOGA_ROOT_DIR" \
+    # Fix 'blinker' issue: cannot uninstall 'blinker': It is a distutils installed project
+    && pip3 install --no-cache-dir --ignore-installed blinker \
+    # Install text-generation-webui and its extensions
+    && pip3 install --no-cache-dir --verbose \
+        -r "$OOBABOOGA_ROOT_DIR/requirements.txt" \
+        -r "$OOBABOOGA_ROOT_DIR/extensions/openai/requirements.txt" \
+    # Install flash-attention
+    && git clone --depth=1 --branch="$FLASH_ATTENTION_BRANCH" https://github.com/Dao-AILab/flash-attention /opt/flash-attention \
+    && git -C /opt/flash-attention apply /tmp/flash-attn.diff \
+    && export FLASH_ATTENTION_FORCE_BUILD=1 \
+    && export FLASH_ATTENTION_FORCE_CXX11_ABI=0 \
+    && export FLASH_ATTENTION_SKIP_CUDA_BUILD=0 \
+    && cd /opt/flash-attention/ \
+    && python3 setup.py install \
+    # Cleanup
+    && rm -rf \
+        /opt/flash-attention \
+        /var/lib/apt/lists/* \
+        "$OOBABOOGA_ROOT_DIR/.git" \
+        "$OOBABOOGA_ROOT_DIR/.github" \
+        "$OOBABOOGA_ROOT_DIR/api-examples" \
+        "$OOBABOOGA_ROOT_DIR/docker" \
+        "$OOBABOOGA_ROOT_DIR/docs" \
+    && apt-get clean
 
-#RUN cd text-generation-webui && \
-#    pip3 freeze > /tmp/constraints.txt && \
-#    pip3 install --no-cache-dir --verbose -r requirements.txt --constraint /tmp/constraints.txt && \
-#    rm /tmp/constraints.txt
-    
-# https://github.com/oobabooga/text-generation-webui/issues/4644
-RUN sed 's|to(self\.projector_device)|to(self\.projector_device,dtype=self\.projector_dtype)|' -i /opt/text-generation-webui/extensions/multimodal/pipelines/llava/llava.py && \
-    cat /opt/text-generation-webui/extensions/multimodal/pipelines/llava/llava.py | grep 'projector_dtype'
-    
-RUN cd text-generation-webui && \
-    sed 's|@functools.cache|@functools.lru_cache\(maxsize=None\)|' -i modules/chat.py && \
-    sed 's|@functools.cache|@functools.lru_cache\(maxsize=None\)|' -i modules/loaders.py && \
-    sed 's|@functools.cache|@functools.lru_cache\(maxsize=None\)|' -i modules/presets.py
+# Copy settings file
+COPY settings.yaml "$OOBABOOGA_ROOT_DIR/"
 
-RUN cp /opt/GPTQ-for-LLaMa/*.py /opt/text-generation-webui
+# Set LD_PRELOAD environment variable
+ENV LD_PRELOAD="${LD_PRELOAD}:${LD_PRELOAD_LIBS}"
 
-# https://github.com/oobabooga/text-generation-webui/issues/3042#issuecomment-1626160643
-#RUN pip3 install --no-cache-dir --verbose 'gradio>=3.36.1'
-RUN pip3 install --no-cache-dir --ignore-installed blinker  # cannot uninstall 'blinker': It is a distutils installed project
-RUN pip3 install --no-cache-dir --verbose -r text-generation-webui/extensions/openai/requirements.txt
-
-RUN if [ -f text-generation-webui/extensions/api/requirements.txt ] ; then \
-	 pip3 install --no-cache-dir --verbose -r text-generation-webui/extensions/api/requirements.txt ; \
-    fi
-
-RUN git clone --depth=1 https://github.com/oobabooga/torch-grammar && \
-    cd torch-grammar && \
-    sed 's|"\^3.9"|"^3.8"|' -i pyproject.toml && \
-    cat pyproject.toml && \
-    pip3 wheel --wheel-dir=dist --no-deps --verbose . && \
-    cp dist/torch_grammar*.whl /opt && \
-    pip3 install --no-cache-dir --verbose /opt/torch_grammar*.whl
-
-ARG LD_PRELOAD_LIBS=""    
-ENV LD_PRELOAD=${LD_PRELOAD}:${LD_PRELOAD_LIBS}
-
-COPY settings.json text-generation-webui/
-
+# Set working directory
 WORKDIR /
 
-CMD /bin/bash -c "cd /opt/text-generation-webui && python3 server.py --model-dir=/data/models/text-generation-webui --listen --verbose"
+# Define command to run the server
+CMD ["/bin/bash", "-c", "cd $OOBABOOGA_ROOT_DIR && python3", "server.py", "--model-dir=$OOBABOOGA_MODEL_DIR", "--listen", "--verbose"]
