save failed builds for inspection and environment cleanup

diff --git a/packages/llm/sglang/Dockerfile b/packages/llm/sglang/Dockerfile
--- a/packages/llm/sglang/Dockerfile
+++ b/packages/llm/sglang/Dockerfile
@@ -2,7 +2,7 @@
 # name: sglang
 # group: llm
 # config: config.py
-# depends: [pytorch, torchvision, torchaudio, transformers, triton:3.1.0, vllm, decord]
+# depends: [pytorch, torchvision, torchaudio, transformers, triton:3.1.0, vllm]
 # requires: '>=34.1.0'
 # test: test.sh
 # notes: https://github.com/sgl-project/sglang
@@ -12,22 +12,21 @@ FROM ${BASE_IMAGE}
 
 ARG SGLANG_VERSION \
     FLASHINFER_VERSION \
-    CUDAARCHS \
-    FORCE_BUILD=off
-
-ENV DEBIAN_FRONTEND=noninteractive \
-    TORCH_CUDA_ARCH_LIST="${CUDAARCHS}" \
     MAX_JOBS="$(nproc)" \
-    CUDA_HOME="/usr/local/cuda/" \
-    PATH="${CUDA_HOME}/bin:${PATH}" \
-    LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
+    FORCE_BUILD=off
 
 RUN apt-get update -y && apt-get install -y libnuma-dev \
     libsndfile1 libsndfile1-dev libprotobuf-dev libsm6 libxext6 libgl1 && \
     rm -rf /var/lib/apt/lists/*
 
 COPY build.sh install.sh /tmp/SGLANG/
-RUN /tmp/SGLANG/install.sh || /tmp/SGLANG/build.sh
+RUN /tmp/SGLANG/install.sh || /tmp/SGLANG/build.sh || touch /tmp/SGLANG/.build.failed
+
+# this retains the stage above for debugging on build failure
+RUN if [ -f /tmp/SGLANG/.build.failed ]; then \
+      echo "SGLANG ${SGLANG_VERSION} build failed!"; \
+      exit 1; \
+    fi
 
 # Default command
 CMD ["/bin/bash"]
