fix: update Dockerfile to clone sdnext repository and configure environment for improved functionality

diff --git a/packages/diffusion/sdnext/Dockerfile b/packages/diffusion/sdnext/Dockerfile
--- a/packages/diffusion/sdnext/Dockerfile
+++ b/packages/diffusion/sdnext/Dockerfile
@@ -11,9 +11,31 @@ FROM ${BASE_IMAGE}
 WORKDIR /opt
 
 # Clone the repository:
-RUN git clone https://github.com/lllyasviel/FramePack /opt/framepack && \
-    cd /opt/framepack && \
+RUN git clone https://github.com/vladmandic/sdnext /opt/sdnext && \
+    cd /opt/sdnext && \
     sed -i 's/==/>=/g' requirements.txt && \
     pip3 install -r requirements.txt
 
-CMD python3 /opt/framepack/demo_gradio.py
+ENV SD_DATADIR="/mnt/data"
+ENV SD_MODELSDIR="/mnt/models"
+
+WORKDIR /opt/sdnext
+# tcmalloc is not required but it is highly recommended
+ENV LD_PRELOAD=libtcmalloc.so.4
+
+RUN ["python3", "launch.py", "--debug", "--uv", "--use-cuda", "--log", "sdnext.log", "--test", "--optional"]
+# preinstall additional packages to avoid installation during runtime
+
+# expose port
+EXPOSE 7860
+
+# actually run sdnext
+CMD ["python3", "launch.py", "--debug", "--skip-all", "--listen", "--quick", "--api-log", "--log", "sdnext.log"]
+
+
+
+
+# healthcheck function
+# HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=3 CMD curl --fail http://localhost:7860/sdapi/v1/status || exit 1
+
+
