updated 'build all' workflows

diff --git a/.github/workflows/build-all_r35.2.1.yml b/.github/workflows/build-all_r35.2.1.yml
--- a/.github/workflows/build-all_r35.2.1.yml
+++ b/.github/workflows/build-all_r35.2.1.yml
@@ -393,6 +393,40 @@ jobs:
           git status 
           ls -a 
        - run: ./build.sh --name=runner/ --push=dustynv l4t-text-generation
+  langchain:
+     name: "langchain"
+     runs-on: [self-hosted, jetson, r35.2.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv langchain
+  langchain-samples:
+     name: "langchain:samples"
+     runs-on: [self-hosted, jetson, r35.2.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv langchain:samples
   llama_cpp-ggml:
      name: "llama_cpp:ggml"
      runs-on: [self-hosted, jetson, r35.2.1]
