updated workflows

diff --git a/.github/workflows/build-all_r35.3.1.yml b/.github/workflows/build-all_r35.3.1.yml
--- a/.github/workflows/build-all_r35.3.1.yml
+++ b/.github/workflows/build-all_r35.3.1.yml
@@ -478,6 +478,40 @@ jobs:
           git status 
           ls -a 
        - run: ./build.sh --name=runner/ --push=dustynv llamaspeak
+  llava:
+     name: "llava"
+     runs-on: [self-hosted, jetson, r35.3.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv llava
+  minigpt4:
+     name: "minigpt4"
+     runs-on: [self-hosted, jetson, r35.3.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv minigpt4
   nemo:
      name: "nemo"
      runs-on: [self-hosted, jetson, r35.3.1]
@@ -1277,6 +1311,40 @@ jobs:
           git status 
           ls -a 
        - run: ./build.sh --name=runner/ --push=dustynv transformers
+  transformers-git:
+     name: "transformers:git"
+     runs-on: [self-hosted, jetson, r35.3.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv transformers:git
+  transformers-nvgpt:
+     name: "transformers:nvgpt"
+     runs-on: [self-hosted, jetson, r35.3.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv transformers:nvgpt
   tritonserver:
      name: "tritonserver"
      runs-on: [self-hosted, jetson, r35.3.1]
