updated docs and workflows

diff --git a/.github/workflows/build-all_r35.3.1.yml b/.github/workflows/build-all_r35.3.1.yml
--- a/.github/workflows/build-all_r35.3.1.yml
+++ b/.github/workflows/build-all_r35.3.1.yml
@@ -223,6 +223,23 @@ jobs:
           git status 
           ls -a 
        - run: ./build.sh --name=runner/ --push=dustynv exllama
+  exllama-v2:
+     name: "exllama:v2"
+     runs-on: [self-hosted, jetson, r35.3.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv exllama:v2
   gptq-for-llama:
      name: "gptq-for-llama"
      runs-on: [self-hosted, jetson, r35.3.1]
@@ -512,6 +529,23 @@ jobs:
           git status 
           ls -a 
        - run: ./build.sh --name=runner/ --push=dustynv minigpt4
+  mlc:
+     name: "mlc"
+     runs-on: [self-hosted, jetson, r35.3.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv mlc
   nemo:
      name: "nemo"
      runs-on: [self-hosted, jetson, r35.3.1]
@@ -1362,6 +1396,23 @@ jobs:
           git status 
           ls -a 
        - run: ./build.sh --name=runner/ --push=dustynv tritonserver
+  tvm:
+     name: "tvm"
+     runs-on: [self-hosted, jetson, r35.3.1]
+     steps:
+       - run: |
+          cat /etc/nv_tegra_release 
+       - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
+         run: |
+          echo "$RUNNER_WORKSPACE" 
+          cd $RUNNER_WORKSPACE 
+          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
+          cd jetson-containers 
+          git fetch origin 
+          git checkout $GITHUB_SHA 
+          git status 
+          ls -a 
+       - run: ./build.sh --name=runner/ --push=dustynv tvm
   xformers:
      name: "xformers"
      runs-on: [self-hosted, jetson, r35.3.1]
