updated ROS build so it saves intermediate build state upon failure

diff --git a/packages/ros/Dockerfile.ros2 b/packages/ros/Dockerfile.ros2
--- a/packages/ros/Dockerfile.ros2
+++ b/packages/ros/Dockerfile.ros2
@@ -25,7 +25,13 @@ RUN python3 -c "import numpy; print('NumPy version:', numpy.__version__)"
 
 # build ROS from source
 COPY ros2_build.sh /tmp/ros2_build.sh
-RUN /tmp/ros2_build.sh
+RUN /tmp/ros2_build.sh || touch /tmp/.ros.build.failed
+
+# this retains the stage above for debugging on build failure
+RUN if [ -f /tmp/.ros.build.failed ]; then \
+      echo "ROS ${ROS_DISTRO} build failed!"; \
+      exit 1; \
+    fi
 
 # Set the default DDS middleware to cyclonedds
 # https://github.com/ros2/rclcpp/issues/1335
